# Generated by Django 2.2.6 on 2020-01-28 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choiice',
            new_name='Choice',
        ),
    ]
