# Generated by Django 3.0.2 on 2020-02-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_choice_citizen_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='voted_questions',
            field=models.ManyToManyField(default=[], to='polls.Question'),
        ),
    ]
